export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'refactor', 'style', 'docs', 'chore', 'build', 'ci', 'perf'],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'home',
        'admin',
        'intro',
        'hero',
        'about',
        'film',
        'memories',
        'gallery',
        'final',
        'content',
        'ui',
        'hooks',
        'lib',
        'types',
        'global',
        'deps',
        'config',
        'i18n',
        'assets',
      ],
    ],
    'scope-empty': [2, 'never'],
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 100],
  },
}
